# Importing NumPy Library in Program

In [4]:
import numpy as np

# Creating array from Lists

In [5]:
arr_1d = np.array([1, 2, 3, 4, 5])
print("1D Array: ",arr_1d)

arr_2d = np.array([[1, 2, 3],[4, 5, 6]])
print("2D Array: ",arr_2d)

1D Array:  [1 2 3 4 5]
2D Array:  [[1 2 3]
 [4 5 6]]


# List vs NumPy Array

In [6]:
py_list = [1,2,3]
print("Muliplicated List:", py_list*2)

np_array = np.array([1,2,3]) #Element wise multiplication
print("Muliplicated List:", np_array*2)

import time
start = time.time()
py_list = [i*2 for i in range(1000000)]
print("\n List operation time:", time.time() - start)

start =  time.time()
np_array = np.arange(100000) * 2
print("\nNumPy Array Operation time:", time.time() - start)

Muliplicated List: [1, 2, 3, 1, 2, 3]
Muliplicated List: [2 4 6]

 List operation time: 0.04375863075256348

NumPy Array Operation time: 0.001142263412475586


# Creating Array from scratch

In [7]:
zeros = np.zeros((3,4))
print("Zeros Array\n",zeros)

ones = np.ones((2,3))
print("\nOnes Array:\n",ones)

full = np.full((2,2),7)
print("\nFull Array\n",full)

random = np.random.random((2,3))
print("\nRandom Array: \n",random)

sequence = np.arange(0,101,2)
print("\nSequence Array\n",sequence)

Zeros Array
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]

Ones Array:
 [[1. 1. 1.]
 [1. 1. 1.]]

Full Array
 [[7 7]
 [7 7]]

Random Array: 
 [[0.98172069 0.21381223 0.24629051]
 [0.34074926 0.95057245 0.24088273]]

Sequence Array
 [  0   2   4   6   8  10  12  14  16  18  20  22  24  26  28  30  32  34
  36  38  40  42  44  46  48  50  52  54  56  58  60  62  64  66  68  70
  72  74  76  78  80  82  84  86  88  90  92  94  96  98 100]


# Vector, Matrix and Tensor

In [8]:
vector = np.array([1,2,3,4,5])
print("\nVector Array:\n",vector)

matrix = np.array([[1, 2, 3],
                   [4, 5, 6]])
print("\nMatrix:\n", matrix)

tensor = np.array([[[1, 2], [3, 4]],
                   [[5, 6],[7, 8]]])
print("\nTensor\n",tensor)


Vector Array:
 [1 2 3 4 5]

Matrix:
 [[1 2 3]
 [4 5 6]]

Tensor
 [[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


# Array Properties

In [15]:
arr = np.array([[1,2,3],
                [4,5,6]])

print("Shape: ",arr.shape)
print("Dimension: ",arr.ndim)
print("Size: ",arr.size)
print("Data Type: ",arr.dtype)

Shape:  (2, 3)
Dimension:  2
Size:  6
Data Type:  int64


# Array Reshaping

In [22]:
arr = np.arange(12)
print("Original Array",arr)

reshaped = arr.reshape(3,4)
print("Reshaped Array:\n",reshaped)

flattened = reshaped.flatten()
print("Flattened Array:\n",flattened)

#Ravel (returns view, instead of copy)
raveled = flattened.ravel()
print("Raveled Array: \n",raveled)

#Transpose
transpose = reshaped.T
print("Transposed Array:\n",transpose)

Original Array [ 0  1  2  3  4  5  6  7  8  9 10 11]
Reshaped Array:
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
Flattened Array:
 [ 0  1  2  3  4  5  6  7  8  9 10 11]
Raveled Array: 
 [ 0  1  2  3  4  5  6  7  8  9 10 11]
Transposed Array:
 [[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]
