# Numpy Array Operations

In [4]:
import numpy as np

In [4]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
print("Basic Slicing:", arr[2:7])
print("Stepping Slicing:", arr[2:9:2])
print("Negative Indexing: ", arr[-3])

Basic Slicing: [3 4 5 6 7]
Stepping Slicing: [3 5 7 9]
Negative Indexing:  8


In [9]:
arr_2d = np.array([[1,2,3],
                   [4,5,6],
                   [7,8,9]])
print("Specific Element:",arr_2d[1,1])
print("Entire Row:",arr_2d[1])
print("Entire Column:",arr_2d[:,1])

Specific Element: 5
Entire Row: [4 5 6]
Entire Column: [2 5 8]


# Sorting

In [17]:
unsorted = np.array([3,2,4,3,7,5,8,6,9,])
print("Sorted Array:",np.sort(unsorted))

arr_2d_unsorted = np.array([[3,1],
                            [1,2],
                            [2,3]])
print("Sorted 2D Array by column\n", np.sort(arr_2d_unsorted, axis=0))
print("Sorted 2D Array by Row\n", np.sort(arr_2d_unsorted, axis=1))

Sorted Array: [2 3 3 4 5 6 7 8 9]
Sorted 2D Array by column
 [[1 1]
 [2 2]
 [3 3]]
Sorted 2D Array by Row
 [[1 3]
 [1 2]
 [2 3]]


# Filter

In [21]:
numbers = np.arange(1,11)
even_numbers = numbers[numbers%2==0]
print(even_numbers)

[ 2  4  6  8 10]


# Filter with Mask

In [24]:
mask = numbers > 5
print("Numbers greater than 5:",numbers[mask])

Numbers greater than 5: [ 6  7  8  9 10]


## Fancy Indexing vs np.where()

In [27]:
indices = [0, 2, 4]
print(numbers[indices])

where_result = np.where(numbers > 5)
print(where_result)
print("NP Where:", numbers[where_result])

[1 3 5]
(array([5, 6, 7, 8, 9]),)
NP Where: [ 6  7  8  9 10]


In [29]:
condition_array = np.where(numbers > 5, numbers*2, numbers)
print(condition_array)

[ 1  2  3  4  5 12 14 16 18 20]


# Adding and removing data

In [5]:
array1 = np.array([1, 2, 3])
array2 = np.array([4, 5, 6])

combined_array = np.concatenate((array1, array2))
print(combined_array)

[1 2 3 4 5 6]


# Array Compatitbility

In [7]:
a = np.array([1,2,3])
b = np.array([4,5,6])
c = np.array([7,8,9])

print("Compatibility Shape: ", a.shape == b.shape)

Compatibility Shape:  True


In [9]:
original = np.array([[1, 2],[3, 4]])

new_row = np.array([[5,6]])

with_new_row = np.vstack((original, new_row))
print(original)
print(with_new_row)

new_col = np.array([[7],[8]])

with_new_column = np.hstack((original, new_col))
print(with_new_column)

[[1 2]
 [3 4]]
[[1 2]
 [3 4]
 [5 6]]
[[1 2 7]
 [3 4 8]]


# Deletion in Array

In [10]:
arr = np.array([1,2,3,4,5])
deleted = np.delete(arr,2)

print(deleted)

[1 2 4 5]
